### ISSUE TITLE
Fix negative fees issue

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#109]
Right now https://live.blockcypher.com/doge/tx/740ee104e465c0a5651f57dffda2c340547bf42e7bcf43c146f6742ee08bd051/ is showing negative 5,526 DOGE fees collected!

![screen shot 2015-04-02 at 9 12 21 pm](https://cloud.githubusercontent.com/assets/448644/6977969/b3551bf8-d97d-11e4-9298-bf253e7002e7.png)

This sounds obviously wrong, so I'm checking the logic from this API call:
https://api.blockcypher.com/v1/doge/main/txs/740ee104e465c0a5651f57dffda2c340547bf42e7bcf43c146f6742ee08bd051
```
{
  "block_hash": "7c3c40d12273e8683385f0f13e6ab30cb0a7033a17a1071b980b76015e80b2ad",
  "block_height": 649967,
  "hash": "740ee104e465c0a5651f57dffda2c340547bf42e7bcf43c146f6742ee08bd051",
  "addresses": [
    "DMFFx8uYx7UYJtFjkShtK4iSa7fSZxCvRh"
  ],
  "total": 1009839937925,
  "fees": 0,
  "preference": "low",
  "relayed_by": "",
  "confirmed": "2015-04-03T03:22:56.810880746Z",
  "received": "2015-04-03T03:22:56.810880746Z",
  "ver": 1,
  "lock_time": 0,
  "double_spend": false,
  "vin_sz": 1,
  "vout_sz": 1,
  "confirmations": 32,
  "confidence": 1,
  "inputs": [
    {
      "output_index": -1,
      "script": "03efea090101062f503253482f",
      "output_value": 1562500000000,
      "sequence": 4294967295,
      "addresses": [],
      "script_type": "empty"
    }
  ],
  "outputs": [
    {
      "value": 1009839937925,
      "script": "210368481ba52f3624a73a3a26c1ecc3097fa6c1c5ca367214dfed7b9246b4f1c4b3ac",
      "addresses": [
        "DMFFx8uYx7UYJtFjkShtK4iSa7fSZxCvRh"
      ],
      "script_type": "pay-to-pubkey"
    }
  ]
}
```

The way we're calculating fees collected on a coinbase transaction is to take the `total` in the JSON above (`1009839937925`) and subtract the value of the first output(`1562500000000`) and then convert that from satoshi. Is this the wrong formula? @matthieu, can you give me the correct formula for coinbase transactions? For non-coinbase I think we're all set.

Btw, related to #105 which is separate.

**Comment by matthieu** [comment]
Fixed.
