### ISSUE TITLE
Subscribe to a transaction (not just an address)

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#111]
Not sure if this is useful (tell me when this broadcast tx has 6 confirms) or an edge case (90% of users who care will subscribe to an address).

@matthieu thoughts?

**Comment by matthieu** [comment]
Yeah, probably an edge case. Don't think people would create a subscription just for a single transaction.

**Comment by mflaxman** [comment]
Ok, closing for now. We can always reopen in the future.
