### ISSUE TITLE
Add search to dasboard

### ISSUE THREAD

**Issue by matthieu** [blockcypher/explorer#112]
When logged in, the dashboard looks pretty bare. Also it's not easy to get back to the search from there. How about including the search bar in there again? So you can still search from your dashboard but also have your stuff.

**Comment by mflaxman** [comment]
Good call

**Comment by mflaxman** [comment]
On second thought, the search bar is in the header and hopefully the dashboard will have more things in it in the future.

Another idea: put a link to the dashboard in the header (for logged in users only), change the blockcypher logo in the header to always point to the homepage (not the dashboard for logged in users), and leave the dashboard as-is. What do you think?

**Comment by matthieu** [comment]
Yes, agree.
