### ISSUE TITLE
Better copy explaining confirmations and tx confidence

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#113]
Also add links to read more somewhere else.

**Comment by mflaxman** [comment]
Paper:
http://www.tik.ee.ethz.ch/file/848064fa2e80f88a57aef43d7d5956c6/P2P2013_093.pdf

**Comment by matthieu** [comment]
Added a more detailed paragraph as well as the link here:

http://dev.blockcypher.com/#zero_confirmations

**Comment by mflaxman** [comment]
Awesome!

This one is for me because I need to simplify that info for the block explorer users (who aren't reading the API docs). Re-opening for me to do that, nothing else for you to do.
