### ISSUE TITLE
Better Setup Instructions

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#114]
Either make the site work with no database locally (it would support a limited set of features) or at the least update the readme to be clearer and work with the latest version of the block explorer.

Thanks to @ChristianGrieger for the nudge!

**Comment by ChristianGrieger** [comment]
Hey @mflaxman,

i can't wait to see that come online! I really would love to build a explorer up for a coin.

Hope to hear from you soon.

Greetings, Christian

**Comment by gjo0117** [comment]
g86

**Comment by mflaxman** [comment]
I've decided instead to disclaimer this as not being easy to setup locally (in 41b517cd9bb4c884dc79dc5636a763e23503dc7f). I run it locally on my own machine, but since that's not a primary use-case I'm not going to invest time in it :(
