### ISSUE TITLE
Password inputs don't trigger password manager in safari

### ISSUE THREAD

**Issue by larrysalibra** [blockcypher/explorer#121]
Password input that show up after confirmation email when subscribing to transaction notification don't trigger keychain or lastpass password managers in safari 8.0.5 on Mac OS X 10.3.3

**Comment by mflaxman** [comment]
Good catch. Do you have this problem on /login as well?

One thing to consider is that the site is built with a graduated
registration process. You don't create an account and then do stuff, doing
stuff gradually creates you an account. Setting a password is the very last
step. So the page where you set the password is rarely one where you enter
a username/email. Is that the source of the problem?

On Tuesday, April 7, 2015, Larry Salibra <notifications@github.com> wrote:

> Password input that show up after confirmation email when subscribing to
> transaction notification don't trigger keychain or lastpass password
> managers in safari 8.0.5 on Mac OS X 10.3.3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blockcypher/explorer/issues/121>.
>


-- 
Sent from my iPhone

**Comment by mflaxman** [comment]
Yup, this works for me on safari on https://live.blockcypher.com/login

I'm closing since I think they just don't support better registration flows.

**Comment by mflaxman** [comment]
Please reopen if you disagree!
