### ISSUE TITLE
Design obscures address spent state label

### ISSUE THREAD

**Issue by larrysalibra** [blockcypher/explorer#122]
"(unspent)" and "(spent)" labels are only partially visible.
https://live.blockcypher.com/btc/block/351101/?page=2
![screen shot 2015-04-07 at 6 07 04 pm](https://cloud.githubusercontent.com/assets/597182/7021150/75a87f20-dd51-11e4-9fba-d3f2443ce507.png)

**Comment by mflaxman** [comment]
Thanks. I pushed an emergency hot fix last week which messed this up. Will
fix.

On Tuesday, April 7, 2015, Larry Salibra <notifications@github.com> wrote:

> "(unspent)" and "(spent)" labels are only partially visible.
>
> [image: screen shot 2015-04-07 at 6 07 04 pm]
> <https://cloud.githubusercontent.com/assets/597182/7021150/75a87f20-dd51-11e4-9fba-d3f2443ce507.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blockcypher/explorer/issues/122>.
>


-- 
Sent from my iPhone
