### ISSUE TITLE
Pagination makes it difficult to browse block transactions

### ISSUE THREAD

**Issue by larrysalibra** [blockcypher/explorer#123]
5 transactions per page and having to click next page to get 5 combined with the sheer vertical space that each transaction takes up makes it tiresome to scroll through transactions.  

For example: this block https://live.blockcypher.com/btc/block/351101/ has 71 pages of transactions.

Perhaps infinite scrolling or at least more transactions per page would improve the experience!

**Comment by mflaxman** [comment]
Infinite scrolling would be awesome but I can get a much easier massive speedup by batching these lookups into one API call. That's why I limit to 5, and the batching feature wasn't available when I built it.

Thanks.

**Comment by mflaxman** [comment]
66217e95a50b16a072f6aa7655c165b45ff34ac7 makes this much faster so I increased it to 10 per page. Does this mostly solve the problem?

Infinite scroll would be better but is not trivial.
