### ISSUE TITLE
Confirmed block txs not in block order

### ISSUE THREAD

**Issue by hbcheng** [blockcypher/explorer#124]
Possibly related to the block ordering issue observed yesterday, transactions within a block are not reported in block order (for example, when reviewing a single block details). This is most easily observed with the coinbase tx which is sometimes 3rd or 4th in the list.

**Comment by mflaxman** [comment]
This should be fixed just now in 2720841487eac13e2c9c4be68a739be00a752dad.

Thanks @hbcheng!

**Comment by hbcheng** [comment]
Can't beat that response time ;) Thanks @mflaxman!
