### ISSUE TITLE
received - sent != balance

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#128]
https://live.blockcypher.com/btc-testnet/address/mtLDA41NWe9rLm7nuMvAnTs2SbP49cz1ZR/

**Comment by mflaxman** [comment]
https://api.blockcypher.com/v1/btc/test3/addrs/mtLDA41NWe9rLm7nuMvAnTs2SbP49cz1ZR

**Comment by quentinlesceller** [comment]
Closing API related.
