### ISSUE TITLE
Use time element with exact time in UI

### ISSUE THREAD

**Issue by larrysalibra** [blockcypher/explorer#132]
![screen shot 2015-04-29 at 7 10 23 pm](https://cloud.githubusercontent.com/assets/597182/7389736/8a64ccf8-eea3-11e4-8f9d-11f3519aea29.png)

Would be great to use the html `time` element with an exact datetime stamp and the exact datetime in the `title` attribute or a javascript tooltip so that people know when "5 months 1 week ago" is.

**Comment by mflaxman** [comment]
Good point @larrysalibra, this was a bug. Thanks for catching!
