### ISSUE TITLE
Double-spends not displaying correctly in AJAX call

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#135]
Discovered here:
https://live.blockcypher.com/btc/tx/7c138bd5179d45bf91ee35d785f6b12444ebfcd76b8f5a32f56e7171de165315/

**Comment by matthieu** [comment]
Yeah, having a red button or something for double-spends would be real cool.

**Comment by matthieu** [comment]
+1

**Comment by mflaxman** [comment]
Fixed in c06582a5d759b30b5ac6e040ebc22c67f2fb2811
