### ISSUE TITLE
Failure to detect double-spend

### ISSUE THREAD

**Issue by adlai** [blockcypher/explorer#151]
Address [1FjWr8qM2fQFf4SNsuWfuAusQmi5txKqee](https://live.blockcypher.com/btc/address/1FjWr8qM2fQFf4SNsuWfuAusQmi5txKqee/) contains three transactions (listed in order of broadcast):
1. ```026b8f6aed1888e970d59337a2b43b88c11e3a761c4880c7bfe4e6d3921daccb``` ([funding](https://live.blockcypher.com/btc/tx/026b8f6aed1888e970d59337a2b43b88c11e3a761c4880c7bfe4e6d3921daccb/))
2. ```dccbf0eb3f82b391e6182c748eccfe0366bf6d6afb20c8c81d284305f1fc67d0``` ([payment](https://live.blockcypher.com/btc/tx/67eee40f07b69027362b056ce04721ea2f69764dee106070023e51c4ca9d0763/))
3. ```67eee40f07b69027362b056ce04721ea2f69764dee106070023e51c4ca9d0763``` ([double-spend](https://live.blockcypher.com/btc/tx/dccbf0eb3f82b391e6182c748eccfe0366bf6d6afb20c8c81d284305f1fc67d0/))

The 2nd transaction will never confirm, yet its "Confidence" score is nonzero, and the info popup reads:

> **Double-Spend Detected:** No
> **Memory Pools With Tx:** 154

Also, the final balance for the address is listed as negative.

**Comment by matthieu** [comment]
The confidence score is still only 1%, which is pretty much as low as it gets and reflects the fact that double-spends can still confirm (not in this case as the other one was confirmed but confidence doesn' factor in what happened on the other leg of a double-spend).

The API has the right info though so that looks like a display bug for @mflaxman.

https://api.blockcypher.com/v1/btc/main/txs/67eee40f07b69027362b056ce04721ea2f69764dee106070023e51c4ca9d0763

**Comment by mflaxman** [comment]
Thanks @adlai and @matthieu.

I'll push a fix soon!

**Comment by mflaxman** [comment]
@matthieu the negative balance is a back-end problem. Can you take a look? It may be similar to #128 which seems to have resolved itself.

**Comment by matthieu** [comment]
Forgot to comment on that. It's just that there was an unconfirmed transaction that was a double spend of another and wasn't confirmed. The unconfirmed balance *can* be negative in some cases, confidence and confirmation are what indicates whether to ignore it or not.

**Comment by mflaxman** [comment]
How can I ignore it? I want to include `unconfirmed_balance` when it might confirm, but not when it can't possibly confirm (double-spend tx has > 6) confs. I think as-is what the API returns is misleading.

https://api.blockcypher.com/v1/btc/main/addrs/1FjWr8qM2fQFf4SNsuWfuAusQmi5txKqee

```
{
  "address": "1FjWr8qM2fQFf4SNsuWfuAusQmi5txKqee",
  "total_received": 7623,
  "total_sent": 7623,
  "balance": 0,
  "unconfirmed_balance": -7623,
  "final_balance": -7623,
  "n_tx": 2,
  "unconfirmed_n_tx": 1,
  "final_n_tx": 3,
  "txrefs": [
    {
      "tx_hash": "dccbf0eb3f82b391e6182c748eccfe0366bf6d6afb20c8c81d284305f1fc67d0",
      "block_height": 377619,
      "tx_input_n": 7,
      "tx_output_n": -1,
      "value": 7623,
      "ref_balance": 0,
      "spent": false,
      "confirmations": 271,
      "confirmed": "2015-10-05T19:36:42Z",
      "double_spend": false
    },
    {
      "tx_hash": "026b8f6aed1888e970d59337a2b43b88c11e3a761c4880c7bfe4e6d3921daccb",
      "block_height": 377522,
      "tx_input_n": -1,
      "tx_output_n": 1,
      "value": 7623,
      "ref_balance": 7623,
      "spent": true,
      "spent_by": "dccbf0eb3f82b391e6182c748eccfe0366bf6d6afb20c8c81d284305f1fc67d0",
      "confirmations": 368,
      "confirmed": "2015-10-05T04:33:37Z",
      "double_spend": false
    }
  ],
  "unconfirmed_txrefs": [
    {
      "address": "1FjWr8qM2fQFf4SNsuWfuAusQmi5txKqee",
      "tx_hash": "67eee40f07b69027362b056ce04721ea2f69764dee106070023e51c4ca9d0763",
      "tx_input_n": 16,
      "tx_output_n": -1,
      "value": 7623,
      "spent": true,
      "spent_by": "026b8f6aed1888e970d59337a2b43b88c11e3a761c4880c7bfe4e6d3921daccb",
      "received": "2015-10-05T18:26:25.893Z",
      "confirmations": 0,
      "double_spend": true,
      "double_spend_tx": "dccbf0eb3f82b391e6182c748eccfe0366bf6d6afb20c8c81d284305f1fc67d0",
      "receive_count": 380,
      "confidence": 0.01,
      "preference": "low"
    }
  ],
  "tx_url": "https://api.blockcypher.com/v1/btc/main/txs/"
}
```
