### ISSUE TITLE
Embed Data server error when no user input

### ISSUE THREAD

**Issue by larrysalibra** [blockcypher/explorer#154]
1. Go to https://live.blockcypher.com/btc/embed-data/
2. Don't type anything in and click the Embed Data button
3. Server error displayed instead of message telling the user to enter some data.

Browser: Safari Version 9.0 (11601.1.56)
OS: Mac OS X 10.11 (15A284)
<img width="1240" alt="screen shot 2015-10-19 at 12 12 07 am" src="https://cloud.githubusercontent.com/assets/597182/10564891/2656cb78-75f6-11e5-9dfb-d4deec8c4091.png">
<img width="1238" alt="screen shot 2015-10-19 at 12 12 19 am" src="https://cloud.githubusercontent.com/assets/597182/10564893/2899d7a4-75f6-11e5-92e1-6f401701dec5.png">

**Comment by mflaxman** [comment]
Good catch, thanks. It's fixed now.

How did you find this feature so quick? It was just pushed like ~1 day ago.

**Comment by larrysalibra** [comment]
I've got my eyes on you @mflaxman ;-)

**Comment by larrysalibra** [comment]
The real answer is: I saw the embed data link while looking for this: https://live.blockcypher.com/btc/tx/b924238993f1a4102d0bf3ea64746df83daa08415b9ad7a49e8e294099351050/

I didn't know what sort of data I could embed and the page didn't tell me, so clicked the Embed Data button with the idea that the error message might give me a hint. :-)

**Comment by mflaxman** [comment]
Awesome!

Please let me know anytime you have block explorer feature requests :)
