### ISSUE TITLE
Add TX Index in Block to Advanced Details of Transaction Page

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#156]
As discussed in #155.

> The index of a transaction within a block is something we already store on the backend, with the transaction. We don't return it in the API yet as no one has cared so far but we could add it easily with pretty much no performance penalty (except the extra bytes).

Waiting on a new endpoint from @matthieu and then I'll add.

**Comment by matthieu** [comment]
Added the `block_index` property, returned for all transactions Example:

http://api.blockcypher.com/v1/btc/main/txs/9495dcbaded91a6fa3e74d4d71fbdb351e309f83aa491403d65769426ea80db5

**Comment by mflaxman** [comment]
@matthieu it's not always showing up?:

https://api.blockcypher.com/v1/btc/main/txs/8a576fb196fe184c1a1841d42471a6e394e888143c7160e395edc0d3bfb39e18
```
{
  "block_hash": "000000000000010046a26006b12510044ac5c1fb87b242e7886e536cce58d99b",
  "block_height": 226039,
  "hash": "8a576fb196fe184c1a1841d42471a6e394e888143c7160e395edc0d3bfb39e18",
  "addresses": [
    "14cZMQk89mRYQkDEj8Rn25AnGoBi5H6uer"
  ],
  "total": 2530355000,
  "fees": 0,
  "size": 122,
  "preference": "low",
  "relayed_by": "",
  "confirmed": "2014-11-27T00:26:46.219Z",
  "received": "2014-11-27T00:26:46.219Z",
  "ver": 1,
  "lock_time": 0,
  "double_spend": false,
  "vin_sz": 1,
  "vout_sz": 1,
  "confirmations": 154175,
  "confidence": 1,
  "inputs": [
    {
      "output_index": -1,
      "script": "03f772030400000b09124d696e656420627920425443204775696c64080000000500001a78",
      "output_value": 2500000000,
      "sequence": 4294967295,
      "script_type": "empty"
    }
  ],
  "outputs": [
    {
      "value": 2530355000,
      "script": "76a91427a1f12771de5cc3b73941664b2537c15316be4388ac",
      "spent_by": "297e863b4ef70e93dc587edf086610e2caa6a870d054f3adde7a067b049e8b99",
      "addresses": [
        "14cZMQk89mRYQkDEj8Rn25AnGoBi5H6uer"
      ],
      "script_type": "pay-to-pubkey-hash"
    }
  ]
}
```

**Comment by mflaxman** [comment]
@matthieu it looks like that's only for coinbase transactions. Not an important use-case, but there's no reason for the property to only sometimes appear.

**Comment by matthieu** [comment]
Ah right. Should be fixed in the next push. The index is zero based btw (so coinbase is at 0).

**Comment by mflaxman** [comment]
That was the 0th thing I noticed when I hooked up to it :)

**Comment by shea256** [comment]
Awesome! I really like how the transaction index starts at zero - I just wish the block height started at zero.
