### ISSUE TITLE
Support for non-HD wallet?

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#161]
Hey @acityinohio and @matthieu, should I do this?

Right now we only have support for HD wallets and it's hidden (only linked to from bcwallet). Example:
https://live.blockcypher.com/bcy/xpub/bpubgo3FGtNgF7qPnXBpEYmZcVYEfrQAEh2BXH5xXTaAqndqbe99PQexs2GimyAfX9q3hHu56yVPCbvuJSMBaHQrRaYaz978UqNq7AujVYQBXQA/?subchain-indices=0-1

The pro argument is that you could create a basket of addresses you want to follow. The con is that I'm not sure what the use-case is (you can already subscribe to a bunch of addresses individually) and maybe you should just do that with the API on your own. The killer feature of the wallet here seems to be the coin selection algo that doesn't really relate to an explorer. The biggest feature would be able to show all your addresses on one page and your total balance, which currently there's no way to do. I could mostly just build this with batching though and not using the wallet API.

That said, if you have a basket of addresses you want to follow, it's probably (or at least should be) an HD wallet. So one option I could have is to make a better UI for the existing HD feature. This will inevitably lead to problems as wallets have different implementations that may not be compatible with our current endpoints (p2sh HD like bitgo, electrum HD wallets which are not bip32), and/or whose implementation is different and will create a wonky UI (bip32 and bip44 wallets use hardened derivation for internal and external chain traversal so a user needs to supply two xpubkeys to track their funds).

Btw, I'll add subscriptions in HD wallets (#160) when I get to #119 and #139.

What should I do? Open to all ideas, not sure how much priority this has.

**Comment by acityinohio** [comment]
Thanks for the detailed question @mflaxman! My personal view is similar to yours: I'd rather folks opted for HD Wallets instead of baskets of individual addresses, and it probably makes more sense to prioritize that view/UI and eventually make it more publicly accessible. With normal wallets, we'd have to provide some method for folks to add their token into the request...and the UX there wouldn't be ideal (and I imagine you'd have to provide a full way to add/remove addresses into wallet, which could be tricky/probably not worth the payoff).

I do recognize the difficulty with dealing with hardened child keys, but I think that might be something that could be dealt with on the UX side by (gracefully) listing the limitations (we only look at one level of derivation, etc). Might be okay to only provide instructions for bip32/44 wallets in this context, since they're the most widely used (and Electrum 2.0+ uses bip32, which makes that argument more defensible).

**Comment by mflaxman** [comment]
> I do recognize the difficulty with dealing with hardened child keys, but I think that might be something that could be dealt with on the UX side by (gracefully) listing the limitations (we only look at one level of derivation, etc). Might be okay to only provide instructions for bip32/44 wallets in this context, since they're the most widely used (and Electrum 2.0+ uses bip32, which makes that argument more defensible).

There are two big issues here:
* In wallets that use hardened derivation (the default) I don't think there's an easy way to get both of your xpub keys (not sure about this). So either we could just leave that up to you (give instructions to go to somewhere like http://bip32.org/ and figure it out) which is a bad UI, or we could ask for your xpriv and derive the xpub (obviously sketchy! even if done with clientside JS, which would be a pain).
* The API only support one xpub per wallet, but these by default use two. Doesn't seem like it makes any sense to showcase this feature unless it's (natively) supported. Otherwise I'll be doing a lot of logic in python to combine the two wallets. Something as simple as getting a transaction history that's sorted by order (in the blockchain) would become complicated as I'd have to manually merge the list of transactions from chain 0 and chain 1.

Does that make sense? All of this points to do nothing for now, which I don't love either :(

Please point out if you think I'm wrong or missing something!

**Comment by acityinohio** [comment]
Good points @mflaxman. Do you think we should offer something like native bip44 support? (https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) The trouble of going down a particular path here (pun kinda intended) at the API level is that I'm not sure there's enough support for a particular bip32 hierarchy yet (bip44 is the most prominent but not universal), and the current HD wallet API is meant to be more general and allow flexibility on the client side...doesn't make it easier for the live explorer though. :-/ I'd say better to not expose it at the live explorer for now and make bcwallet the flagship demo for the HD Wallet API.

**Comment by mflaxman** [comment]
> Do you think we should offer something like native bip44 support? 

Yes, I do. Right now, an HD wallet can support multiple sub-chains. I see no reason to not have support for multiple xpubs (say with no subchain).

With the current implementation, if I had a few coin on each of my chains (some was change from TXs I'd sent and some was coin I'd received but never touched) and I wanted to send it all, it'd be impossible to build a TX using the API! I'd have to build one TX getting everything from hardened chain 0 and another TX getting everything from hardened chain 1. That just makes no sense.

Does that make sense?

**Comment by matthieu** [comment]
It does but that's not very high in the list of people have asked for (at least to me). What I've heard the most about regarding HD is: we do HD with multisig, hence we can't use your stuff.

**Comment by mflaxman** [comment]
Makes sense @matthieu . I'll close this for now. Nothing for the explorer to do.

If the wallet API one day support multiple chains then perhaps people would want to do watching-only versions of their HD wallet (perhaps with subscriptions, too).
