### ISSUE TITLE
[Feature Request] BIP101 is now activated on testnet, support would be appreciated

### ISSUE THREAD

**Issue by rromanchuk** [blockcypher/explorer#166]
It would be nice if you could show block size here for a bip101 block

https://live.blockcypher.com/btc-testnet/block/0000000000305b7fb149b6faa8b37613f104e3b6eccdf60848e99f8c6e29e451/

**Comment by jtoomim** [comment]
(That was the block that forked testnet, by the way.)

**Comment by matthieu** [comment]
Block size is on our list, we just need to add it to the API first. After that we can report it in the explorer and have a maybe a specific color or icon for block sizes > 1Mb.

**Comment by jtoomim** [comment]
Cool, thanks.

**Comment by syaifudin85** [comment]
Join syaif5061@gmail.com

**Comment by quentinlesceller** [comment]
Block size is there now.
