### ISSUE TITLE
Switch to API Call sans Addresses on TX for speed

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#167]
Waiting for endpoint from @matthieu

**Comment by tonnymontana** [comment]
> Waiting for endpoint from @matthieu 
> 

3MDFNM31WJqDwkXubkLv9uHJfuxjujX4KN

**Comment by samsungbiologics** [comment]
f854aebae95150b379cc1187d848d58225f3c4157fe992bcd166f58bd5063449

**Comment by samsungbiologics** [comment]
curl https://api.blockcypher.com/v1/btc/main/txs/f854aebae95150b379cc1187d848d58225f3c4157fe992bcd166f58bd5063449

{
"block_hash": "0000000000000000c504bdea36e5...",
"block_height": 293000,
"hash": "f854aebae95150b379cc1187d848d58225f...",
"addresses": [
  "13XXaBufpMvqRqLkyDty1AXqueZHVe6iyy",
  "19YtzZdcfs1V2ZCgyRWo8i2wLT8ND1Tu4L",
  "1BNiazBzCxJacAKo2yL83Wq1VJ18AYzNHy",
  "1GbMfYui17L5m6sAy3L3WXAtf1P32bxJXq",
  "1N2f642sbgCMbNtXFajz9XDACDFnFzdXzV"
],
"total": 70320221545,
"fees": 0,
"size": 636,
"preference": "low",
"relayed_by": "",
"confirmed": "2014-03-29T01:29:19Z",
"received": "2014-03-29T01:29:19Z",
"ver": 1,
"lock_time": 0,
"double_spend": false,
"vin_sz": 4,
"vout_sz": 1,
"confirmations": 64373,
"inputs": [
  {
  "prev_hash": "583910b7bf90ab802e22e5c25a89b59...",
  "output_index": 1,
  "script": "4830450220504b1ccfddf508422bdd8b0f...",
  "output_value": 16450000,
  "sequence": 4294967295,
  "addresses": [
    "1GbMfYui17L5m6sAy3L3WXAtf1P32bxJXq"
  ],
  "script_type": "pay-to-pubkey-hash"
  },
  ...
],
"outputs": [
  {
  "value": 70320221545,
  "script": "76a914e6aad9d712c419ea8febf009a3f3...",
  "spent_by": "35832d6c70b98b54e9a53ab2d51176eb...",
  "addresses": [
    "1N2f642sbgCMbNtXFajz9XDACDFnFzdXzV"
  ],
  "script_type": "pay-to-pubkey-hash"
  }
]
}

**Comment by khokho1986** [comment]
0xEbb764A49BCCE1Bb8E805d2151b70AbD19F4725f

**Comment by khokho1986** [comment]
> 3AhLfoVCK1UcA8VjCDu6r1ZQTLEdVq3LPc

BTC
