### ISSUE TITLE
UTXO for address includes the same UTXO multiple times from orphans

### ISSUE THREAD

**Issue by bharathrao** [blockcypher/explorer#168]
https://api.blockcypher.com/v1/btc/test3/addrs/2NGFWxipuq85dzoTjJiRGNWAkmGhhYiXLJu?unspentOnly=true

474e6ed0fca2710885dbaabbeb66dc3a0b39fa5891a37da5f5c810768bd80d14 output 0 is included 3 times, 2 from orphan blocks 

https://www.blocktrail.com/tBTC/tx/474e6ed0fca2710885dbaabbeb66dc3a0b39fa5891a37da5f5c810768bd80d14

**Comment by matthieu** [comment]
The testnet has been very problematic lately with constant long forks and the XT hard fork activation. We've cleaned that up a bit, removing dups.
