### ISSUE TITLE
AttributeError: module 'html.parser' has no attribute 'HTMLParseError' 

### ISSUE THREAD

**Issue by rromanchuk** [blockcypher/explorer#171]
Python 3.5 issue it looks like 

https://gist.github.com/thefourtheye/2205fe8ff7974e2cebf6

**Comment by mflaxman** [comment]
@rromanchuk thanks or the bug report. Can you show where this is happening and/or how to duplicate?

This is the codebase that runs on https://live.blockcypher.com and I can't find that error in the logs.

Thanks!

P.S. The site runs on 3.3.5:
https://github.com/blockcypher/explorer/blob/0ce26280518f3d4d8d5285756308dd5864819835/runtime.txt

**Comment by suhailvs** [comment]
`HTMLParseError` is deprecated from `Python 3.3` onwards and removed in `Python 3.5`, as per the [official documentation](https://docs.python.org/3/library/html.parser.html#html.parser.HTMLParseError). The fix has been already delivered to the [code repository](https://github.com/django/django/commit/b07aa52e8a8e4c7fdc7265f75ce2e7992e657ae9).

so used **Django 1.8+** or manually fix it by looking at the [commit](https://github.com/django/django/commit/b07aa52e8a8e4c7fdc7265f75ce2e7992e657ae9).
