### ISSUE TITLE
Detect Omni OP_RETURN payloads

### ISSUE THREAD

**Issue by dexX7** [blockcypher/explorer#175]
Hi there,

it would be nice, if blockcypher could detect Omni (formerly Mastercoin) transactions, such as [this](https://live.blockcypher.com/btc/tx/cb3e5d22c6704689ee2d30e863053c898c5f487578c0c4b5ecd958a819b21edf/) one.

Omni transactions use the OP_RETURN prefix 0x6f6d6e69 ("omni").

I took a quick look at the source code, but I'm not sure where [transaction.data_protocol](https://github.com/blockcypher/explorer/blob/586427d1c861bad59ed823453b2c1014a993bb86/templates/transaction_overview.html#L72-L87) is coming from, and if you point me in the right direction, I'd be happy to create a pull request.

**Comment by mflaxman** [comment]
Thanks for the feature request @dexX7!

The blockcypher API doesn't yet support Omni as a data protocol, but @acityinohio is going to add it soon. Then it will be trivial to display this.

**Comment by acityinohio** [comment]
It's been merged and in production! Thanks again for the feedback @dexX7.

**Comment by dexX7** [comment]
Thanks guys, really appreciated! :)
