### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by newbyprogrammer** [blockcypher/explorer#177]
Is there any tutorial or place where explain how to install this explorer?

I am trying to install with the readme and I can't

Thanks

**Comment by mflaxman** [comment]
Sorry @newbyprogrammer , the block explorer is open source but not designed to be easy to run locally. I've updated the readme in 41b517cd9bb4c884dc79dc5636a763e23503dc7f.

For understanding how this works, I'd recommend http://dev.blockcypher.com/?python , which documents every single method call.
