### ISSUE TITLE
Request: Transaction API add ancestorsize and ancestorfees from getrawmempool

### ISSUE THREAD

**Issue by dabura667** [blockcypher/explorer#192]
in bitcoind, getrawmempool verbose mode gives you two helpful pieces of info, ancestorsize and ancestorfees.

This is basically the size in bytes including the transaction at hand and all unconfirmed parent transactions (recursive) and the total fees in satoshis of all unconfirmed parents (also including the queried transaction)

This is very useful for calculating extra fees needed for CPFP.

I would suggest something where the two values are only given if the transaction is not confirmed, and if the transaction is confirmed, both values give 0.

Having one API call instead of using recursive API call promises to traverse the unconfirmed parent tree would be nice.

**Comment by syaifudin85** [comment]
bc1qss243rfw8v0xa4qj4jdruv0clvjrmgj4jndg0s

**Comment by quentinlesceller** [comment]
Closing not going to implement it now.
