### ISSUE TITLE
Add Bitcoin Cash

### ISSUE THREAD

**Issue by Olsm** [blockcypher/explorer#196]
When will you add Bitcoin Cash to your api?

**Comment by 121889** [comment]
NATAWUT
i do you  BTC 0.00102000  .ONO

**Comment by Olsm** [comment]
It is already #3 on coinmarketcap. Will you add it please?
Thank you so much in advance! :)

**Comment by Olsm** [comment]
Can you add it please?
I need it to accept 0 confirm transactions using your transaction confidence api.

**Comment by zquestz** [comment]
Would be great to see this added.

**Comment by ChaosElephant** [comment]
Bitcoin Cash in the api would really be awesome.

**Comment by amandris** [comment]
Bitcoin is no longer an option for merchants. Please add bitcoin cash to your api.

**Comment by maesitos** [comment]
+1 We are for the moment using Blocktrail.com but we'd love to also like to add support for BCH thought Blockcypher's adapter in our Rails crypto app https://github.com/Sailias/bitcoin_payable

**Comment by maesitos** [comment]
+1 We are for the moment using Blocktrail.com but we'd love to also add support for BCH through Blockcypher's adapter in our Rails crypto app https://github.com/Sailias/bitcoin_payable

**Comment by syaifudin85** [comment]
Bitcoin bc1qss243rfw8v0xa4qj4jdruv0clvjrmgj4jndg0s

**Comment by quentinlesceller** [comment]
Thank you for creating an issue but this is not on our roadmap at the moment.
