### ISSUE TITLE
QR code always creates with bitcoin protocol

### ISSUE THREAD

**Issue by IBlackI** [blockcypher/explorer#201]
https://github.com/blockcypher/explorer/blob/19aff669e9fe69543e915c2bd5499bcbc008da67/templates/address_overview.html#L90
As seen on this line the qr code generates with bitcoin:ADRESS. Even when using a litecoin adress, possibly resulting in a app sending the wrong crypto

**Comment by carbontwelve** [comment]
I just discovered this today...

**Comment by syaifudin85** [comment]
bc1qss243rfw8v0xa4qj4jdruv0clvjrmgj4jndg0s

**Comment by sema0703** [comment]
> https://github.com/blockcypher/explorer/blob/19aff669e9fe69543e915c2bd5499bcbc008da67/templates/address_overview.html#L90
> 
> 
> As seen on this line the qr code generates with bitcoin:ADRESS. Even when using a litecoin adress, possibly resulting in a app sending the wrong crypto
