### ISSUE TITLE
https://live.blockcypher.com/btc/tx/9025082d12ff7381b4aa459e3457962ef587c92d60ceafb2ad9d410ee47130f9/

### ISSUE THREAD

**Issue by ivastres** [blockcypher/explorer#206]
Close  main 1  post ?

Not recevie confrim main BTC  14 Hour ??

Wath hapen

**Comment by matthieu** [comment]
We are not responsible for the bitcoin network and how transactions get confirmed. Please stop creating github issues that aren't related to this software.
