### ISSUE TITLE
Error 500 when subscribing to address

### ISSUE THREAD

**Issue by The-Compiler** [blockcypher/explorer#210]
When trying to subscribe at https://live.blockcypher.com/btc/address/1PMzbcetAHfpxoXww8Bj5XqquHtVvMjJtE/ (without an account) I get a 500 internal server error.

**Comment by syaifudin85** [comment]
Please fix the problem.

**Comment by syaifudin85** [comment]
bc1qss243rfw8v0xa4qj4jdruv0clvjrmgj4jndg0s

**Comment by quentinlesceller** [comment]
Not supported anymore.
