### ISSUE TITLE
Account setup broken

### ISSUE THREAD

**Issue by The-Compiler** [blockcypher/explorer#211]
I just tried creating an account. First I got "This account already exists, please log in" or so, which I'm pretty sure isn't true.

Then I tried logging in, and got a "This account doesn't have a password set" message.

When trying to do so, I got an internal server error.

**Comment by mddulalhosen6** [comment]
getcoin how accept

**Comment by Literarytech** [comment]
I would also add that my new account is not sending the verification email. It has been about an hour and I still do not have it.

**Comment by syaifudin85** [comment]
Please correct me to login? Or send to Syai coinbace wallet

**Comment by quentinlesceller** [comment]
Hi, we are disabling the email subscription service for addresses. Closing.
