### ISSUE TITLE
Serious bug in your system

### ISSUE THREAD

**Issue by williambanks** [blockcypher/explorer#213]
Sorry to reach out this way but all my emails to you are bouncing and thus, coming to your only active repo to report this seems to be the only way to reach out.

I'm currently paying $500 USD per month for your enterprise class plan and getting this error...
https://pastebin.com/Jh9q46Fj

Please address the issue or I will not be renewing my subscription when it comes due and I will be taking to reddit, twitter, facebook and steemit to explain why we're moving away from you (hint an enterprise plan comes with an expectation of the ability to communicate with you, you need to whitelist the domains of paying customers).

Thanks!

You can email me wbanks@vivaco.in to inform me of the resolution, before closing this issue.

**Comment by syaifudin85** [comment]
Send to syaif5061@gmail.com account roof wallet coinbace syai
