### ISSUE TITLE
blockcypher has not sent email to my email account  to let verify the email

### ISSUE THREAD

**Issue by jasontwtin** [blockcypher/explorer#218]

**Comment by hopeseekr** [comment]
Yeah, me neither. Maybe the service is abandoned?

**Comment by troianb** [comment]
Same here!

**Comment by hopeseekr** [comment]
Based upon my investigations over the last 2 weeks, it appears that @BlockCypher has abandoned their fiscal and custodial responsibilities to all clients. No one may even be manning the ship! Defintely don't leave crypto there!

**Comment by syaifudin85** [comment]
When I was a bitcoin wallet or wallet coinbace syai

**Comment by quentinlesceller** [comment]
Hi, we are disabling the email subscription service for addresses.
