### ISSUE TITLE
Mail non confermata

### ISSUE THREAD

**Issue by Luca22bo** [blockcypher/explorer#220]
Salve,ho un piccolissimo problema con la mia mail su blockcypher,dice che non ho mai confermato l'indirizzo per cui non posso fare molto. E' possibile ottenere nuovamente la mail di conferma? 
Oppure è possibile inviare i Litecoin presenti sul mio dashboard,su un altro a mia scelta?
Se si,potreste mandarmi le istruzioni per eseguire il ritiro del saldo del mio conto?

Questa è l'immagine che esce quando accedo al sito
![block](https://user-images.githubusercontent.com/34650435/34106564-f5f0a710-e3f8-11e7-99f1-cf2bce7434f8.png)

**Comment by syaifudin85** [comment]
Please fix me to be able to send to me syaif5061@gmail.com or wallet coinbace syai
