### ISSUE TITLE
Litecoins stuck and unspent. Need help to send it back to my wallet

### ISSUE THREAD

**Issue by nem052** [blockcypher/explorer#222]
My litecoins has not been sent but it shows confirmation , need help to send it to destination address or return it to my wallet

**Comment by Bryanbxbuhu** [comment]
Just had the same Issue, I sent litecoin to a wallet in Kraken that disappeared.

**Comment by ketanbitcoin0112** [comment]
Mine too showing as unspent, what is wrong with this Litecoin coin, transaction  confirmed and unspent. Too bad. https://live.blockcypher.com/ltc/address/LZVTeZ9TCUe1SwStxrpzegurg4NKPv9RVf/

Let me know if you received them and how?

**Comment by powerfun62** [comment]
I have same problem, confirmed but unspent, shows a balance on blockcypher

**Comment by mohsenbanak** [comment]
My litecoins has not been sent but it shows confirmation , need help to send it to destination address or return it to my wallet

**Comment by innnzzz6** [comment]
https://live.blockcypher.com/ltc/address/LVcHVehKU4iUez4YzM5eidR9j9VW74kipw/

Help me .. please . My ltc stuck too.. please return to given address ..thanks support

**Comment by suiody** [comment]
843c4863b40b7ee0a08519b4b63e979508986ad3367d779a1a9f97ab8028cc94

**Comment by petkatedinev** [comment]
843c4863b40b7ee0a08519b4b63e979508986ad3367d779a1a9f97ab8028cc94

**Comment by innnzzz6** [comment]
Thanks for help  i put to metatada right?
