### ISSUE TITLE
LOST MY LITECOIN WHILE TRANSFERRING FROM WALLET

### ISSUE THREAD

**Issue by anasmodi** [blockcypher/explorer#225]
I HAD LOST MY 1 LITE COIN TRANSFER FROM MY WALLET TO ELECTRUM  LTC WALLET

WHEN I COPIED MY RECIVING ADDRESS,
IT PASTES ANOTHER ADDRESS SHOWN BELOW

Lca8Rse1xKK8fsMmZp78rrN4HxbggMP7cf

BUT WHEN I CHECKED MY WALLET MY BALACE IS 0 LTC, AND THE ABOVE DISPALYED ADDRESS IS NOT MINES .

SO HOW DO I GET MY 1 LITECOIN BACK 
PLEASE DO HELP .

**Comment by r7avi** [comment]
forget it ,

**Comment by sugianoor** [comment]
help me
