### ISSUE TITLE
Add BIP173 support

### ISSUE THREAD

**Issue by youssefgh** [blockcypher/explorer#226]
Bech32 addresses are now getting more support and adoption from the community due to the tx size optimization which translate to less fees
An example of a tx: 834dce8d6e9f5323af8f00869220c357bc8540ecfd8d868261da15f4a6c6ba2d
The block explorer doesn't show the destination address nor accept it in the UI or API searches
Any plans already exist for  BIP173 ?
Thanks

**Comment by festus1973** [comment]
Have you had any breakthroughs on this? I'm about to nix BlockCypher in favor of another free API (BlockChair) that offers bech32 support. BlockCypher has ceased responding to all email queries, although I'm not sure whether or not they've abandoned the project entirely. Would love to hear one way or the other.

**Comment by youssefgh** [comment]
@festus1973 i think that there is no intention to add bech32. Its good to know that BlockChair support it. I myself moved to Electrumx

**Comment by matthieu** [comment]
There is definitely an intention to support Bech32. The timing of it however isn't set yet, but hopefully soon.

**Comment by festus1973** [comment]
> @festus1973 i think that there is no intention to add bech32. Its good to know that BlockChair support it. I myself moved to Electrumx

Hi, youssefgh... It's been a while since our last convo. Just wanted to see if you're still using ElectrumX (or any other Bitcoin APIs for that matter) that supports Bech32? I've been having good luck with BlockChair as my primary but it would be nice to have a backup. Looks like BlockCypher still isn't suitable for non-trivial projects due to lack of Bech32 support, although it _is_ able to push raw SegWit transactions so I still use it for that purpose. What are your current Bitcoin API providers?

**Comment by youssefgh** [comment]
hello @festus1973 
am still using electrumx server (you can run your own or use one of the public [testnet](https://1209k.com/bitcoin-eye/ele.php?chain=tbtc) or [mainet](https://1209k.com/bitcoin-eye/ele.php?chain=btc) ones) check [my wallet](https://github.com/youssefgh/mooo-wallet) to see how 
since electrumx doesn't support Rest, i had to create a java proxy to convert Rest calls to Json-rpc over TCP calls, check it out [here](https://github.com/youssefgh/tcp-rest-proxy)
You can test that live on [testnet](http://testnet.wallet.mooo.tech) or [mainnet](http://wallet.mooo.tech)

**Comment by quentinlesceller** [comment]
BlockCypher now fully supports BIP173. Closing.
