### ISSUE TITLE
Subscribe via website threw HTTP error, email verification never received

### ISSUE THREAD

**Issue by acowpy** [blockcypher/explorer#227]
Hi guys
I tried subscribing to a Litecoin address yesterday but a HTTP error (500 if I remember correctly) was thrown and the email verification was never received.
Now I'm getting this when I login:
`Your email address (aaron@shop-grok.com) has not been confirmed, email notifications will not be sent.`
But there is no option to resend the verification email.
Cheers

**Comment by syaifudin85** [comment]
Please fix my account syaif5061@gmail.com and send or send syai wallet coinbace

**Comment by quentinlesceller** [comment]
Hi, we are disabling the email subscription service for addresses. Closing.
