### ISSUE TITLE
LTC coins transaction confirmed 6 time but unspent, not appearing in wallet, and no further process.

### ISSUE THREAD

**Issue by ketanbitcoin0112** [blockcypher/explorer#228]
https://live.blockcypher.com/ltc/address/LZVTeZ9TCUe1SwStxrpzegurg4NKPv9RVf/

I have made a transaction in LTC from HItbtc and now though transaction got 6 confirmation it got stuck as unspent, it is happening to lots of people, 9 other transaction in same block are unspent.

Litecoin claims transaction fast in 10 to 20 min., mine is taking more then a day.

Please help me and let me know how i can get my coins back as early as possible.

Regards.

**Comment by suiody** [comment]
https://live.blockcypher.com/show-widgets/ltc/LZVTeZ9TCUe1SwStxrpzegurg4NKPv9RVf/

2018-01-20 18:58 GMT+03:00 ketanbitcoin0112 <notifications@github.com>:

**Comment by miltonc90** [comment]
i also have this issue coming from HitBTC sending to Electrum-LTC

here is the link to the transaction ID on the LTC blockchain
https://live.blockcypher.com/ltc/address/LPSPRZvLsADKTKmV3EhHxsW16592d4dRgK/

did you ever resolve this problem?  could it be a technical problem on electrum-LTC's side?

**Comment by miltonc90** [comment]
Updating my electrum app resolved it.  It wasn't syncing

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 19, 2020 at 9:50, Quentin Le Sceller<notifications@github.com> wrote:   
Closed #228.
