### ISSUE TITLE
Lite coin missing

### ISSUE THREAD

**Issue by maheshdokala** [blockcypher/explorer#233]
I have send lite coin to zebpay. it is showing unspend. Please let me know how can i get it.

REFERENCE NUMBER:  1fed7c2a6a5b8a76095fcde286f882eac3b3f21e82d40bff463b1e23fc318748

**Comment by maheshdokala** [comment]
My Lite coin address is 3ANurQogcWu2HmdpBGNc5we2LsLfAW7Sa4

2 Outputs Created
1.0 LTC to
 3ANurQogcWu2HmdpBGNc5we2LsLfAW7Sa4 (unspent)

**Comment by ashwilly** [comment]
I know someone who once helped me recover funds stolen from my wallet, I'm guessing it's like same procedure, you can email him on cheng66@protonmail.ch
