### ISSUE TITLE
Been nearly 24 hours and have not heard or received papal I bought 

### ISSUE THREAD

**Issue by troianb** [blockcypher/explorer#234]
102 confirmed and no contact made, nothing. Help!

**Comment by Online-d** [comment]
Ich hatte lange zeit Problem mit meiner Passwort.
Ich habe Problem aufgehoben bitte um kontackt.

troianb <notifications@github.com> schrieb am Mo., 05.03.2018, 8:15:

**Comment by troianb** [comment]
English please?

**Comment by zhtet036** [comment]
1C76qHBjywP7vNbyzhvKsnvoouTHa1Vtx

**Comment by zhtet036** [comment]
qqppn2cxn2lld7m4692xg0ylfejt5arpkvzdtfqj62
