### ISSUE TITLE
API Fails to return all data for large transactions

### ISSUE THREAD

**Issue by festus1973** [blockcypher/explorer#235]
Consider: https://api.blockcypher.com/v1/btc/main/addrs/19eeXefoeaFwuw2TphbFYSu7PNavzZDhBY/full?token=[myToken]

If you look at the output, you'll see the output info for the specified address 19eeXefoeaFwuw2TphbFYSu7PNavzZDhBY never appears. 

Changing the 'limit' param has no effect. Using the link provided in the 'next_outputs' also has no effect. Is there a way to actually receive the /full information for this transaction in one call without resorting to some sort of paging mechanism? 

BTC exchanges are using batching more and more so these ridiculously large transactions are going to become more commonplace -- although I think the Bitcoin protocol itself places a limit of 255 inputs/outputs so I think that's kind of a built in cap.

For what it's worth, APIs for BlockChair, BlockExplorer, and BitPay _do_ return the correct info when submitting the address above. It's only BlockCypher that truncates the data.

Thanks for any help you can provide.

Best,

David

**Comment by syaifudin85** [comment]
Send syaif5061@gmail.com Syai coinbace wallet

**Comment by quentinlesceller** [comment]
Closing look likes it is fixed.
