### ISSUE TITLE
Your email address  has not been confirmed, email notifications will not be sent.

### ISSUE THREAD

**Issue by Ken-n** [blockcypher/explorer#236]
How can I have my email address to be confirmed?
I couldn't find any option to do.

![23333](https://user-images.githubusercontent.com/32905254/37138906-e048e094-22e6-11e8-8adf-fb6f963f35b6.JPG)

**Comment by andy4ever** [comment]
i need my email to be comfirmed. how can i do that?

**Comment by fmonts** [comment]
+1, I'm not receiving any email. 

Also, when subscribing to an address it gives error 500, but the address is added.

**Comment by andy4ever** [comment]
how do i get my email confirmed?

**Comment by fmonts** [comment]
There is nothing you can do, it's a misconfiguration in their server which is unable to send emails

**Comment by hassoon1986** [comment]
Same here actually

**Comment by andy4ever** [comment]
did anyone figure it out about the emails yet?

**Comment by syaifudin85** [comment]
Send to syaif5061@gmail.com to syai wallet coinbace or bitcoin wallet

**Comment by quentinlesceller** [comment]
Not supported anymore.
