### ISSUE TITLE
USDT

### ISSUE THREAD

**Issue by aghamir** [blockcypher/explorer#237]
Hi, 
I see blockcypher is showing omnilayer transactions and detect it. So is there any possiblity that blockcypher can detect tether transactions and shows the value as tether instead of BTC?
Thanks a lot for your awsome api!

**Comment by petkatedinev** [comment]
Благодаря много за вашия awsome api

**Comment by syaifudin85** [comment]
Send to syaif5061@gmail.com account

**Comment by quentinlesceller** [comment]
Hi @aghamir thanks for the feature request. However this is not on our roadmap right now.
