### ISSUE TITLE
Please support multiple address lookup

### ISSUE THREAD

**Issue by dan-da** [blockcypher/explorer#245]
I am the author of [hd-wallet-addrs](https://github.com/dan-da/hd-wallet-addrs), a tool for finding all addresses in an HD wallet that have ever received funds.

I just now integrated blockcypher.com into the tool as a blockchain data provider.  Unfortunately, the one-address-per request limitation slows the tool to a crawl.  I am referring to this type of query:

https://api.blockcypher.com/v1/btc/main/addrs/1Ge6rDuyCdYVGhXZjcK4251q67GXMKx6xK

I have found a couple blockchain data providers that do support multi-address lookups, namely blockchain.info and btc.com.  I hope we can bring blockcypher's performance in the tool up to the same speed as these provide.  Especially as it is possible to self-host blockcypher code.  This would give people the possibility to run the tool in a totally private way.

I'm sure that multi-address lookups would benefit others as well.  Mine is just one use case example.

thanks!

**Comment by matthieu** [comment]
Have you tried batching?

**Comment by dan-da** [comment]
hmm, still open.  any chance of increasing batch limit to a reasonable level, eg 20 for the addrs api?

**Comment by matthieu** [comment]
How much you can have in the batch depends on your rate plan. Each element in the batch counts individually for a request, so you just need to have a high enough per-second limit.

**Comment by dan-da** [comment]
@matthieu I think if you read my comments in detail you would see I am already well aware of blockcypher's paid options and that's not something I'm interested for my free/open source tool.  Fortunately there are alternatives to blockcypher.  thx anyway.
