### ISSUE TITLE
WebSockets events not working

### ISSUE THREAD

**Issue by lucafalasco** [blockcypher/explorer#248]
It seems like all standard WebSockets events listed [here](https://www.blockcypher.com/dev/bitcoin/#types-of-events) are not currently working, as shown in the test below:

![ws-test](https://user-images.githubusercontent.com/4623726/44617517-faef1000-a863-11e8-9649-ff25fca0666b.gif)

I can only get a correct response when sending the `{ "event": "ping" }` message.

##### perhaps related to #247

**Comment by ab77** [comment]
Related?
https://stackoverflow.com/questions/52275678/blockcypher-websocket-endpoint-not-working

**Comment by quentinlesceller** [comment]
Related https://github.com/blockcypher/node-client/issues/27. Will leave that issue open.

**Comment by quentinlesceller** [comment]
You must have a TOKEN after the query. It will works without token but you'll quickly reach your limit.
