### ISSUE TITLE
How to extract addresses from raw transactions.

### ISSUE THREAD

**Issue by ghost** [blockcypher/explorer#249]
I would like to do it in offline.
currently when using bitcoin-tx -json $txrawstring i'm getting output addresses but not input addresses. How to get them. I would like to do it in offline , not on blockcypher.

**Comment by ravibhojwani** [comment]
USE GOOGLE

**Comment by Anisaazza** [comment]
kenapa saat saya melakukan penarikan ke alamat saya tidak juga masuk sampai sekarang
💵 Withdraw  
🔹 Investor: Hasan
🔹Amount:0.0008182
view transaction
