### ISSUE TITLE
Why is the transaction amount of unconfirmed_txrefs inquiring out inconsistent with the actual amount?

### ISSUE THREAD

**Issue by waliguder** [blockcypher/explorer#251]
api:https://api.blockcypher.com/v1/eth/main/addrs/0x11131E33fE4b585d346f106700303DE6f1AB2a84
I found that the amount of the unconfirmed transaction queried with the api is inconsistent with the amount of the actual transaction sent, but after the transaction is confirmed, the amount is restored to the correct value？？？

**Comment by syaifudin85** [comment]
Send syaif5061@gmail.com to syai wallet coinbace
