### ISSUE TITLE
Need confermation on 

### ISSUE THREAD

**Issue by Saltygangsta** [blockcypher/explorer#259]
On dec 4 at 2:31am theres a transaction that still needs all 3 confermations its perventing me from making any withdrawals from my sportsbet.io account it was a deposit for 15mb please can this be fix it in my sportsbet.io. transaction # is 9dc578adb547c0dd6c47c6e87d739c62a85c6e12e764266bbf579ea770c090b5

**Comment by mrnhoz** [comment]
DUGda5YRs1i2LcdEeXaPq1tV8KQcrsrGF8

**Comment by Saltygangsta** [comment]
no I'm receiving it I'm having trouble with the process I've never done it
this way because the btc machine wodnt scan my btc barcode

**Comment by Saltygangsta** [comment]
please don't close this I never knew there is a time limit
