### ISSUE TITLE
LTC M-address?

### ISSUE THREAD

**Issue by oti-dev** [blockcypher/explorer#264]
Hello,

What's the reason for the Litecoin block explorer to use old-fashioned 3-address encoding instead of new M-address? Are there any issues with using the M-addresses?

**Comment by quentinlesceller** [comment]
M-Addresses are now supported: https://www.blockcypher.com/dev/bitcoin/#transaction-hash-endpoint. On July first the block explorer will only use maddrs. You can already look up for maddrs and that should work.
