### ISSUE TITLE
718{"error": "Not enough signatures: 0 for 1 inputs"}

### ISSUE THREAD

**Issue by dutyk** [blockcypher/explorer#270]
when I use "https://api.blockcypher.com/v1/bcy/test/txs/send?“ to send transactions, it occurs this problem, I don't know why?

**Comment by syaifudin85** [comment]
Please correct and send to account

**Comment by quentinlesceller** [comment]
You need to sign the provided data. More info in our dev documentation =>https://www.blockcypher.com/dev/bitcoin/
