### ISSUE TITLE
Paid for goods in shop with a auto button who pastes adress and ammount straight into my wallet. But it sent the wrong adress. 

### ISSUE THREAD

**Issue by Fukiduki** [blockcypher/explorer#276]
It all comes down to that the ebshops autoburron which pastes the adress and ammount into my wallet has given my the wrong adress. The exact ammount is sitting there in Blockcypher without been touched.

How do I solve this? It was a pretty good ammount of money so I would really like to get them back or complete the deal with the store.

Can anyone help me in the right direction?

**Comment by hktoor1** [comment]
1AoudgVPfpnC79iMVuCdUPjKHkFRA8quN9

‏‫من الـ iPhone الخاص بي‬

‫في 22‏/06‏/2019 الساعة 3:14 م، كتب/كتبت ‏Fukiduki ‏<notifications@github.com>:‬
