### ISSUE TITLE
Dash explorer stuck

### ISSUE THREAD

**Issue by KonstantinRyazantsev** [blockcypher/explorer#277]
Dash explorer is not updated for 3 dyas:

![image](https://user-images.githubusercontent.com/10830510/59964529-c3e09e00-950a-11e9-81ad-722864ccf647.png)

Other dash explorers work fine.

**Comment by hktoor1** [comment]
1AoudgVPfpnC79iMVuCdUPjKHkFRA8quN9

‏‫من الـ iPhone الخاص بي‬

‫في 22‏/06‏/2019 الساعة 4:27 م، كتب/كتبت ‏Konstantin Ryazantsev ‏<notifications@github.com>:‬

**Comment by ivanmfan** [comment]
I wrote email about this situation, and don't receive answer, who know when it will be fix?

**Comment by greatwolf** [comment]
Both Dash and Dogecoin explorer are stuck. They're both over 2 weeks behind on blocks.

**Comment by quentinlesceller** [comment]
Fixed.
