### ISSUE TITLE
Installation fails due to conflicting bitcoin version

### ISSUE THREAD

**Issue by NeolithEra** [blockcypher/explorer#279]
Hi, users are unable to run explorer due to dependency conflict with _**bitcoin**_ package. 

As shown in the following full dependency graph of **_explorer_** , **_explorer_** requires _**bitcoin==1.1.29**_，while **_blockcypher==1.0.73_** requires _**bitcoin==1.1.39**_.

According to pip’s “first found wins” installation strategy, _**bitcoin==1.1.29**_ (the latest version) is the actually installed version. 
However, _**bitcoin==1.1.29**_ does not satisfy _**bitcoin==1.1.39**_.

### Dependency tree-------
```
explorer(version range:)
| +-bitcoin(version range:==1.1.29)
| +-blockcypher(version range:==1.0.73)
| | +-requests(version range:==2.4.3)
| | +-python-dateutil(version range:==2.2)
| | | +-six(version range:)
| | +-bitcoin(version range:==1.1.39)
| +-dj-database-url(version range:==0.3.0)
| +-dj-static(version range:==0.0.6)
| | +-static3(version range:)
| +-django(version range:==1.7.1)
| +-django-annoying(version range:==0.8.0)
| +-django-crispy-forms(version range:==1.4.0)
| +-django-debug-toolbar(version range:==1.2.2)
| +-django-storages(version range:==1.1.8)
| +-django-toolbelt(version range:==0.0.1)
| | +-django(version range:)
| | +-psycopg2(version range:)
| | +-gunicorn(version range:)
| | | +-sphinx(version range:)
| | | +-sphinx-rtd-theme(version range:)
| | +-dj-database-url(version range:)
| | +-dj-static(version range:)
| | | +-static3(version range:)
| +-gnureadline(version range:==6.3.3)
| +-gunicorn(version range:==19.1.1)
| +-ipython(version range:==2.3.0)
| +-jsonfield(version range:==1.0.2)
| +-newrelic(version range:==2.36.0.30)
| +-psycopg2(version range:==2.7.1)
| +-python-dateutil(version range:==2.2)
| | +-six(version range:)
| +-python-postmark(version range:==0.4.7)
| +-pytz(version range:==2014.9)
| +-raven(version range:==5.1.1)
| +-requests(version range:==2.4.3)
| +-six(version range:==1.9.0)
| +-sqlparse(version range:==0.1.13)
| +-static3(version range:==0.5.1)
| +-wheel(version range:==0.24.0)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1. Fix your direct dependency to be **_bitcoin==1.1.39_**. 
I have checked this revision will not affect your downstream projects now.

2. Remove your direct dependency **_bitcoin==1.1.29_** and use the bitcoin==1.1.39 transitively introduced by blockcypher==1.0.73.

Which solution do you prefer, 1 or 2 ?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by bozerk23** [comment]
###

**Comment by acityinohio** [comment]
> ### Solution
> 1. Fix your direct dependency to be **_bitcoin==1.1.39_**.
>    I have checked this revision will not affect your downstream projects now.
> 2. Remove your direct dependency **_bitcoin==1.1.29_** and use the bitcoin==1.1.39 transitively introduced by blockcypher==1.0.73.
> 
> Which solution do you prefer, 1 or 2 ?
> @acityinohio Please let me know your choice. I can submit a PR to solve this issue.

Appreciate the response but I don't have any access to this repo anymore/no longer work for BlockCypher, perhaps @matthieu or someone else from BlockCypher can help out.

**Comment by syaifudin85** [comment]
Send to 
Account or syai wallet coinbace

**Comment by quentinlesceller** [comment]
@NeolithEra working on an updated version now.

**Comment by quentinlesceller** [comment]
Fixed with latest version.
