### ISSUE TITLE
error ngrok

### ISSUE THREAD

**Issue by h2o10** [blockcypher/explorer#304]
`vm@h2o10:~# sudo apt-get install postgresql libpq-dev ngrok-client ngrok-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ngrok-client
E: Unable to locate package ngrok-server`

**Comment by quentinlesceller** [comment]
We don't offer support for installing your own version of the explorer. You might not need ngrok-server anymore.
