### ISSUE TITLE
Link to the BTC testnet faucet returns 404

### ISSUE THREAD

**Issue by andreishtamburg** [blockcypher/explorer#305]
On BTC testnet transaction page there is a link to the `Free Bitcoin Testnet Faucet`.
`https://accounts.blockcypher.com/testnet-faucet`.

It leads to the `Page not found`

![image](https://user-images.githubusercontent.com/61147894/83619175-c4dbd580-a58b-11ea-9474-4e88a887c3d2.png)

**Comment by quentinlesceller** [comment]
Indeed the faucet is not running anymore. I'll delete the link.

**Comment by parin13** [comment]
@quentinlesceller  what is the point of having it in API documentation then? Please remove it asap, it is misleading the community

**Comment by quentinlesceller** [comment]
@parin13 Fixed.

**Comment by parin13** [comment]
@quentinlesceller  still getting the errror:
`{"error": "Error building faucet transaction: Not enough funds in 0 inputs to pay for 1 outputs, missing -10000.."}`
for 
`curl -d '{"address": "mwbiDnK1tQfhz9vTz6UwkSH9NmD3Ho4uM6", "amount": 10000}' https://api.blockcypher.com/v1/btc/test3/faucet?token=mytoken
`

**Comment by quentinlesceller** [comment]
Hi @parin13 I answered your initial message which is:

> @quentinlesceller what is the point of having it in API documentation then? Please remove it asap, it is misleading the community

So I removed it from the doc. Our test3 faucet is discontinued you can find several faucets online.
