### ISSUE TITLE
Gaming Addresses with Thousands of Transactions are Breaking

### ISSUE THREAD

**Issue by ghost** [blockcypher/explorer#31]
http://blockcypher.herokuapp.com/btc/address/1LuckyR1fFHEsXYyx5QK4UFzv3PEAepPMK/

**Comment by Mujeeb506** [comment]
Hye i was send 0.077 something ltc to payeer status is done from coinbase but my money stuck here. Receiver​ id is  # 
LPTeFL5ALEP9xV9NdqUdb1fYXtEHaQM7tR
Please solved the problem and complete transaction

**Comment by Mujeeb506** [comment]
![Screenshot_2020-09-12-01-23-51](https://user-images.githubusercontent.com/71152194/92969599-b8262200-f496-11ea-8a2f-715d8c76dae3.png)
Please complete this transaction
