### ISSUE TITLE
Access denied on address endpoint with ?limit=2

### ISSUE THREAD

**Issue by D-Nice** [blockcypher/explorer#310]
Works: https://api.blockcypher.com/v1/eth/main/addrs/738d145faabb1e00cf5a017588a9c0f998318012?limit=3

Doesn't work: https://api.blockcypher.com/v1/eth/main/addrs/738d145faabb1e00cf5a017588a9c0f998318012?limit=2

Haven't tested on other endpoints, but one can avoid this issue via `?after=0&limit=2`

**Comment by quentinlesceller** [comment]
That's strange. Thanks for letting us know!

**Comment by quentinlesceller** [comment]
Fixed.
