### ISSUE TITLE
repsonse body batch balance false

### ISSUE THREAD

**Issue by VolckaertAchiel** [blockcypher/explorer#317]
when executing this call, the response body contains a comma that shouldn't be there.

https://api.blockcypher.com/v1/btc/test3/addrs/2N7ryJmXqMfBfpzxHviWGbZ8XgtAJioMz5G;2N7o9dAc1LTjzcJri4ZLgbuH7bngGsoZL4b;2MxrYJfQCsw4JfjDRCeZWLpwTrkbTiEsPXX;2NDyuBWdkEarZjjwTNt4CapaPUK2Ci7uXF2;2MtjEj7xXCbDmhDNjCGbcFaYvdtt5PYpgRR;/balance

[
    {
        "address": "2N7ryJmXqMfBfpzxHviWGbZ8XgtAJioMz5G",
        "total_received": 300000,
        "total_sent": 0,
        "balance": 300000,
        "unconfirmed_balance": 0,
        "final_balance": 300000,
        "n_tx": 3,
        "unconfirmed_n_tx": 0,
        "final_n_tx": 3
    },
    {
        "address": "2MtjEj7xXCbDmhDNjCGbcFaYvdtt5PYpgRR",
        "total_received": 0,
        "total_sent": 0,
        "balance": 0,
        "unconfirmed_balance": 0,
        "final_balance": 0,
        "n_tx": 0,
        "unconfirmed_n_tx": 0,
        "final_n_tx": 0
    },
    ,
    {
        "address": "2N7o9dAc1LTjzcJri4ZLgbuH7bngGsoZL4b",
        "total_received": 0,
        "total_sent": 0,
        "balance": 0,
        "unconfirmed_balance": 0,
        "final_balance": 0,
        "n_tx": 0,
        "unconfirmed_n_tx": 0,
        "final_n_tx": 0
    },
    {
        "address": "2MxrYJfQCsw4JfjDRCeZWLpwTrkbTiEsPXX",
        "total_received": 0,
        "total_sent": 0,
        "balance": 0,
        "unconfirmed_balance": 0,
        "final_balance": 0,
        "n_tx": 0,
        "unconfirmed_n_tx": 0,
        "final_n_tx": 0
    },
    {
        "address": "2NDyuBWdkEarZjjwTNt4CapaPUK2Ci7uXF2",
        "total_received": 0,
        "total_sent": 0,
        "balance": 0,
        "unconfirmed_balance": 0,
        "final_balance": 0,
        "n_tx": 0,
        "unconfirmed_n_tx": 0,
        "final_n_tx": 0
    }
]

**Comment by quentinlesceller** [comment]
Hi @VolckaertAchiel, thank you for the bug report. Indeed looks like something went wrong ! I'm going to close that issue and transfer it on our core platform repo (private though :)). But be sure it's duly noted.

**Comment by VolckaertAchiel** [comment]
@quentinlesceller when can we see this resolved?

**Comment by quentinlesceller** [comment]
hey @VolckaertAchiel actually your query is incorrect. Remove the `;` at the end and it should be good.
