### ISSUE TITLE
DASH P2SH addresses ('7') not recognized

### ISSUE THREAD

**Issue by Felix0301** [blockcypher/explorer#318]
All P2SH DASH addresses are labelled 'InvalidAddress' - even if they have transactions.

E.g. 
https://live.blockcypher.com/dash/tx/0b5ea6079cfca7f5ffeef5860be50fb485660354a8572c405bc1cf8b83c23ac8/ 
Vout 1 goes to 7YJ823k4kW3mj7VtKG2e6pnUHFauBfBTQq, but:
https://live.blockcypher.com/dash/address/7YJ823k4kW3mj7VtKG2e6pnUHFauBfBTQq/
returns 'Invalid Address'

**Comment by quentinlesceller** [comment]
Fixed in https://github.com/blockcypher/explorer/commit/a72de29c06694a3a3c176d22ea3d342a24c3b965 and deployed

**Comment by samsungbiologics** [comment]
{
  "address": "7YJ823k4kW3mj7VtKG2e6pnUHFauBfBTQq",
  "total_received": 3581631878,
  "total_sent": 3581631878,
  "balance": 0,
  "unconfirmed_balance": 0,
  "final_balance": 0,
  "n_tx": 2,
  "unconfirmed_n_tx": 0,
  "final_n_tx": 2,
  "txrefs": [
    {
      "tx_hash": "2455ad30a667f727b8c0df969e4c235f41964f9399ed1e65e3049220877ce45d",
      "block_height": 1349693,
      "tx_input_n": 5,
      "tx_output_n": -1,
      "value": 3581631878,
      "ref_balance": 0,
      "confirmations": 55727,
      "confirmed": "2020-10-05T15:59:49Z",
      "double_spend": false
    },
    {
      "tx_hash": "0b5ea6079cfca7f5ffeef5860be50fb485660354a8572c405bc1cf8b83c23ac8",
      "block_height": 1349572,
      "tx_input_n": -1,
      "tx_output_n": 1,
      "value": 3581631878,
      "ref_balance": 3581631878,
      "spent": true,
      "spent_by": "2455ad30a667f727b8c0df969e4c235f41964f9399ed1e65e3049220877ce45d",
      "confirmations": 55848,
      "confirmed": "2020-10-05T10:52:02Z",
      "double_spend": false
    }
  ],
  "tx_url": "https://api.blockcypher.com/v1/dash/main/txs/"
}
