### ISSUE TITLE
Unconfirmed Transaction 

### ISSUE THREAD

**Issue by hasbi204** [blockcypher/explorer#323]
I made a transaction via API and my transaction was not confirmed for a very long time, until now it is still unconfirmed. When I checked in explorer, the confidence was 45%. Will my transaction fail or will it be sent? please help and solution, I am still a beginner.

Txid: 
https://live.blockcypher.com/doge/tx/07e58509a270e92facedd463b964dd35246775eeb2662de395cfe446dca84857

**Comment by herihendrayana** [comment]
Great your projec

**Comment by quentinlesceller** [comment]
Looks like your transaction didn't make it into a block. Try with higher fees next time.
