### ISSUE TITLE
error in pushing the transaction : json cannot unmarshal object into go value of type ()json rawmessage

### ISSUE THREAD

**Issue by parin13** [blockcypher/explorer#325]
I wanted to push the transaction to blockcypher using api : `https://api.blockcypher.com/v1/btc/test3/txs/send
` but i am getting this error, i believe it is error in the blockcypher side as i am sending the payload as per the [documentation](https://www.blockcypher.com/dev/bitcoin/?javascript#txref). Here is my [payload](https://pastebin.com/uXukMqtX) :

`
{
   "tx":{
      "block_height":-1,
      "block_index":-1,
      "hash":"e20b05d2bd249908b4087677c346a516d15df45326d715bf77dbe4a8f5182268",
      "addresses":[
         "mwbiDnK1tQfhz9vTz6UwkSH9NmD3Ho4uM6",
         "moC17MzbvgUJAZWEqoRiJJ8S7YdxyeXoVL"
      ],
      "total":39800,
      "fees":4200,
      "size":160,
      "preference":"low",
      "relayed_by":"103.94.220.70",
      "received":"2020-11-28T20:21:07.119679792Z",
      "ver":1,
      "double_spend":False,
      "vin_sz":2,
      "vout_sz":2,
      "confirmations":0,
      "inputs":[
         {
            "prev_hash":"d77dbb6130d9cb260e764bbaa40b9148dc14ab5b5f6eb309883afe6d6ba10db5",
            "output_index":0,
            "output_value":22000,
            "sequence":4294967295,
            "addresses":[
               "mwbiDnK1tQfhz9vTz6UwkSH9NmD3Ho4uM6"
            ],
            "script_type":"pay-to-pubkey-hash",
            "age":1892387
         },
         {
            "prev_hash":"6c47c17b5c9808b689a27883469d689d61ae9dec95b9867664cc175283ab1ba5",
            "output_index":0,
            "output_value":22000,
            "sequence":4294967295,
            "addresses":[
               "mwbiDnK1tQfhz9vTz6UwkSH9NmD3Ho4uM6"
            ],
            "script_type":"pay-to-pubkey-hash",
            "age":1892387
         }
      ],
      "outputs":[
         {
            "value":29999,
            "script":"76a914542b7411dc7407ac8f1f3214e42e92f6086a26dc88ac",
            "addresses":[
               "moC17MzbvgUJAZWEqoRiJJ8S7YdxyeXoVL"
            ],
            "script_type":"pay-to-pubkey-hash"
         },
         {
            "value":9801,
            "script":"76a914b0685821057edba67be4b4271c62c4dd9b649ae888ac",
            "addresses":[
               "mwbiDnK1tQfhz9vTz6UwkSH9NmD3Ho4uM6"
            ],
            "script_type":"pay-to-pubkey-hash"
         }
      ]
   },
   "tosign":[
      "a0b018a42053bcf04976faadce6f3a534692460fdf5e92fbf1cd288cfc73d318",
      "89e7cecf1c562a2903b38eef3d1032f596f2caa57e415af6a2b88bcb9d0934ac"
   ],
   "signatures":[
      [
         "304402201bd9a08b3da2afa4bf7b644a742b1baf369b3c3291861638923edaa357c93c8102200ce33045a8616affefdfd919f441b3bc50d3ce4eb89bddfc680150c40a34b472",
         "3044022000801d7e9c1b104107bf5d3a0bd5d3c5983c67027f5906d9353cb4309a677c0f02203ce237cf0a2c3afc48c9f520d717de1974d13f6fb675b51e5133170d7a61bea6"
      ]
   ],
   "pubkeys":[
      [
         "0277a7bced1af7d1baa5e18d9900ce0e5b47ee50c7002c8265e01c64afd105a7d3",
         "0277a7bced1af7d1baa5e18d9900ce0e5b47ee50c7002c8265e01c64afd105a7d3"
      ]
   ]
}
`

**Comment by parin13** [comment]
@quentinlesceller can you please address this issue

**Comment by quentinlesceller** [comment]
Hi Parishilan,

Your data structure is incorrect.

1. It's "false" and not "False" (no uppercase F). The latter is invalid in JSON

2. The signatures is NOT a double array.

3. The pubkeys is NOT a double array.

The payload should look like that:
```JSON
{
    "tx": {
        "block_height": -1,
        "block_index": -1,
        "hash": "e20b05d2bd249908b4087677c346a516d15df45326d715bf77dbe4a8f5182268",
        "addresses": [
            "mwbiDnK1tQfhz9vTz6UwkSH9NmD3Ho4uM6",
            "moC17MzbvgUJAZWEqoRiJJ8S7YdxyeXoVL"
        ],
        "total": 39800,
        "fees": 4200,
        "size": 160,
        "preference": "low",
        "relayed_by": "103.94.220.70",
        "received": "2020-11-28T20:21:07.119679792Z",
        "ver": 1,
        "double_spend": false,
        "vin_sz": 2,
        "vout_sz": 2,
        "confirmations": 0,
        "inputs": [
            {
                "prev_hash": "d77dbb6130d9cb260e764bbaa40b9148dc14ab5b5f6eb309883afe6d6ba10db5",
                "output_index": 0,
                "output_value": 22000,
                "sequence": 4294967295,
                "addresses": [
                    "mwbiDnK1tQfhz9vTz6UwkSH9NmD3Ho4uM6"
                ],
                "script_type": "pay-to-pubkey-hash",
                "age": 1892387
            },
            {
                "prev_hash": "6c47c17b5c9808b689a27883469d689d61ae9dec95b9867664cc175283ab1ba5",
                "output_index": 0,
                "output_value": 22000,
                "sequence": 4294967295,
                "addresses": [
                    "mwbiDnK1tQfhz9vTz6UwkSH9NmD3Ho4uM6"
                ],
                "script_type": "pay-to-pubkey-hash",
                "age": 1892387
            }
        ],
        "outputs": [
            {
                "value": 29999,
                "script": "76a914542b7411dc7407ac8f1f3214e42e92f6086a26dc88ac",
                "addresses": [
                    "moC17MzbvgUJAZWEqoRiJJ8S7YdxyeXoVL"
                ],
                "script_type": "pay-to-pubkey-hash"
            },
            {
                "value": 9801,
                "script": "76a914b0685821057edba67be4b4271c62c4dd9b649ae888ac",
                "addresses": [
                    "mwbiDnK1tQfhz9vTz6UwkSH9NmD3Ho4uM6"
                ],
                "script_type": "pay-to-pubkey-hash"
            }
        ]
    },
    "tosign": [
        "a0b018a42053bcf04976faadce6f3a534692460fdf5e92fbf1cd288cfc73d318",
        "89e7cecf1c562a2903b38eef3d1032f596f2caa57e415af6a2b88bcb9d0934ac"
    ],
    "signatures": [
        "304402201bd9a08b3da2afa4bf7b644a742b1baf369b3c3291861638923edaa357c93c8102200ce33045a8616affefdfd919f441b3bc50d3ce4eb89bddfc680150c40a34b472",
        "3044022000801d7e9c1b104107bf5d3a0bd5d3c5983c67027f5906d9353cb4309a677c0f02203ce237cf0a2c3afc48c9f520d717de1974d13f6fb675b51e5133170d7a61bea6"
    ],
    "pubkeys": [
        "0277a7bced1af7d1baa5e18d9900ce0e5b47ee50c7002c8265e01c64afd105a7d3",
        "0277a7bced1af7d1baa5e18d9900ce0e5b47ee50c7002c8265e01c64afd105a7d3"
    ]
}
```

Closing.
