### ISSUE TITLE
LOW SKILL

### ISSUE THREAD

**Issue by samsungbiologics** [blockcypher/explorer#329]
Copy & Paste. will do it copy paste

**Comment by alizeyni** [comment]
f854aebae95150b379cc1187d848d58225f3c4157fe992bcd166f58bd5063449

در تاریخ جمعه ۱۵ ژانویهٔ ۲۰۲۱،‏ ۱۲:۱۳ samsungbiologics <
notifications@github.com> نوشت:

**Comment by hktoor1** [comment]
الاخ علي ممكن تتواصل معي بصفه عاجله 
هذا ايميلي 
hwwabard@hotmail.com
