### ISSUE TITLE
status confirmed but (unspent) #1

### ISSUE THREAD

**Issue by teeqoze** [blockcypher/explorer#331]
I contact you because I received 200€ LTC my status is confirmed but I did not receive my money on coinbase and it is displayed (unspent) how I can do to unlock this

https://live.blockcypher.com/ltc/tx/6569cd39b76969c29f849a91c593984632f0adcf558a73a72492ce85777f4a6b/

**Comment by teeqoze** [comment]
Why u closed the post i dont receveid the litcoins

**Comment by skrappy1511** [comment]
Ay how do you mine bitcoin or any cryptocurrency ...or how do you receive
it while mining??tryna learn
