### ISSUE TITLE
LTC send to BTC adress 

### ISSUE THREAD

**Issue by teeqoze** [blockcypher/explorer#332]
Hello , I contact you because I have a big problem I just transferred me 1.63755865 LTC on a BTC address unfortunately I did not have any error message can you do something I absolutely need this money

https://live.blockcypher.com/ltc/tx/6569cd39b76969c29f849a91c593984632f0adcf558a73a72492ce85777f4a6b/

**Comment by hktoor1** [comment]
Unfortunately, I did not understand you

**Comment by teeqoze** [comment]
> Unfortunately, I did not understand you

i send 1.6 LTC to a BTC adress how i can resolve that

**Comment by sodikinpro** [comment]
You send me 50000 dogecoin. IM send bek

**Comment by teeqoze** [comment]
?

**Comment by teeqoze** [comment]
why u closethis ????? i dont receveid my LTC @quentinlesceller
