### ISSUE TITLE
DOGE Transaction have no confirmation whatsoever

### ISSUE THREAD

**Issue by HanzHaxors** [blockcypher/explorer#335]
Blockcypher TX: [link](https://live.blockcypher.com/doge/tx/af2d844cb9c194c8d3523088c9aff8bd175bccfa8a7eae4cf95e8c1feeb0c94e/)
Blockchair TX: [link](https://blockchair.com/dogecoin/transaction/af2d844cb9c194c8d3523088c9aff8bd175bccfa8a7eae4cf95e8c1feeb0c94e)

I use coinb.in as the client to broadcast and fetch UTXO from blockcypher, i never use blockchair but its for comparison.

**Comment by quentinlesceller** [comment]
We had a chain lag for several days. This is fixed.
