### ISSUE TITLE
show the scripts hex when clicking on "advanced details" of a tx

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#34]
From email thread "Stealth Address?"

**Comment by mflaxman** [comment]
You wrote in an email to me:
> It'd be nice to show the scripts hex too when clicking on "advanced details" btw.

I responded:
> I like this idea but the current design only allows details on the whole transaction and not each of the inputs/ouputs, so we'd need to design something for it. Added to github for the not-immediate future. For now there is the link on every page to the API call that generated it, so that gives the user something to go on.

I don't think other explorers show the script hex on the main output for good reason, and if you want that the link to the API is there.

It'd be easy to include, just worrying it would clog up the page so I want to be sure I understand the use-case. What's the thinking here? Another option is I could make it some sort of a mouse-over so you don't see it by default (less clutter).

I separately am a fan of #78 but that's the tx hex (not the script hex), so totally different.

**Comment by matthieu** [comment]
Yes, let's start with #78 and revisit this later if it still makes sense.
