### ISSUE TITLE
Missing genesis block

### ISSUE THREAD

**Issue by jsarenik** [blockcypher/explorer#356]
Hi there!

[The first Ethereum block](https://live.blockcypher.com/eth/block/1/) does not link to its ancestor (the [genesis](https://live.blockcypher.com/eth/block/11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa) [block](https://live.blockcypher.com/eth/block/0) where the gigantic pre-mine happened and which is correctly [listed at etherscan](https://etherscan.io/txs?block=0) and [mentioned by bitquery.io](https://bitquery.io/blog/get-ethereum-total-supply#Total_pre-mined_Eth) as well). 

Reference: https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3622

See also the [article](https://www.swanbitcoin.com/why-bitcoin-is-not-a-ponzi-scheme-point-by-point/) which points out the Ethereum pre-mine. Someone may want to check the block where it happened also on BlockCypher ETH explorer.

Thank you!

**Comment by quentinlesceller** [comment]
Indeed good catch. Too bad you remove it from bitcoin.org but heh I like mempool.space too...

**Comment by jsarenik** [comment]
@quentinlesceller blockcypher was not removed from bitcoin.org, mempool.space was just added. See https://bitcoin.org/en/resources

**Comment by jsarenik** [comment]
For reference, this was the merged PR: https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3623

**Comment by jsarenik** [comment]
@quentinlesceller And thank you for your peaceful reaction. I admit being frustrated when I wrote this issue right after realizing ETH pre-mine (though I never had any, but feel sorry for those who do).

**Comment by Damian8610** [comment]
3CcYvX3K8nnc4xKcqDwK69LuW621YsWNst

**Comment by jsarenik** [comment]
@Damian8610 what is this?

**Comment by jsarenik** [comment]
@Damian8610 https://mempool.space/address/3CcYvX3K8nnc4xKcqDwK69LuW621YsWNst but why here?

**Comment by jsarenik** [comment]
@Damian8610 did you want to say something like "Hi guys! I will be happy to work on this issue, but need funds so that I can buy bread and sustain my life…" ?

**Comment by jsarenik** [comment]
Reopening. The issue is still present.

**Comment by quentinlesceller** [comment]
We are working on a new version of API for Ethereum so this issue will not be fixed in the near future.
