### ISSUE TITLE
dogecoin fee

### ISSUE THREAD

**Issue by maede71** [blockcypher/explorer#363]
Hi
"Current Fee Estimates" for dogecoin not true.
Low Priority: 0.00045 DOGE/KB 
Medium Priority: 3.45977 DOGE/KB 

The range of change is enormous
When the transaction is done with a low amount, it is never possible to confirm within the network.

**Comment by maede71** [comment]
resolve it : transactionBuilder.StandardTransactionPolicy.MaxTxFee = null;
help:
https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin.Tests/transaction_tests.cs

**Comment by quentinlesceller** [comment]
Hi @maede71,

Thanks for letting us know. This is now fixed.

Closing.
