### ISSUE TITLE
Where's my doge?

### ISSUE THREAD

**Issue by quetevalgah** [blockcypher/explorer#372]
Wth! Still haven't received my doge!! 😩 6+ confirmations and nothing. Ahhh

**Comment by Yessika224** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by hktoor1** [comment]
My dear brother, did he really offer you assistance in recovering your money, and did he ask you in return﻿
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111
