### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by Eddieglover** [blockcypher/explorer#438]
I have an issue with dogexlive 
I have money owing to me and it just seems stuck. Please help me ?

**Comment by hktoor1** [comment]
Like you, if you know the solution, help me‫في 23‏/01‏/2023 الساعة 9:31 م، كتب/كتبت ‏Eddieglover ***@***.***>:‬﻿
I have an issue with dogexlive
I have money owing to me and it just seems stuck. Please help me ?

**Comment by Eddieglover** [comment]
I do not have a solution to this problem yet. I have engaged with block cypher. Good luck

**Comment by Yessika224** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111
