### ISSUE TITLE
I would like all my assets applied to my account please

### ISSUE THREAD

**Issue by SimmonsServices41** [blockcypher/explorer#459]
https://explorer.bnbchain.org/assets/bep8?utm_source=tokenpocket

**Comment by Yessika224** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by kdove527** [comment]
the issue is nigers that are greedy 
    On Monday, May 8, 2023, 7:14:44 AM PDT, Quentin Le Sceller ***@***.***> wrote:  
 
 


Closed #459 as completed.
