### ISSUE TITLE
unspent litecoin in blockcypher 

### ISSUE THREAD

**Issue by mahamfatima753** [blockcypher/explorer#471]
I have made a transaction in LTC from coinbase and now though transaction got 6 confirmation it got stuck as unspent,  why it is happening to lots of people.

https://live.blockcypher.com/ltc/address/LQ4kgQLay3rJCM1fjhZFLxgQEmXgJVf1sV/

**Comment by cheetooooo** [comment]
بتاريخ ٠١‏/٠٧‏/٢٠٢٣ ٧:٢٢ ص، كتب mahamfatima753 ***@***.***>:
Closed #471 as completed.

**Comment by mahamfatima753** [comment]
> بتاريخ ٠١‏/٠٧‏/٢٠٢٣ ٧:٢٢ ص، كتب mahamfatima753 ***@***.***>: Closed #471 as completed. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

MY ISSUE IS NOT SOLVED NOW
