### ISSUE TITLE
LTC coins transaction confirmed 6 time but unspent, not appearing in wallet, and no further process

### ISSUE THREAD

**Issue by mahamfatima753** [blockcypher/explorer#472]
https://live.blockcypher.com/ltc/address/LQ4kgQLay3rJCM1fjhZFLxgQEmXgJVf1sV/

I have made a transaction in LTC from Coinbase and now though transaction got 6 confirmation it got stuck as unspent, it is happening to lots of people, 9 other transaction in same block are unspent.

Litecoin claims transaction fast in 20to 30 min., mine is taking more then a day.

Please help me and let me know how i can get my coins back as early as possible. please

**Comment by herohero1232** [comment]
@mahamfatima753 Talk to LTC Support on the [Litecointalk live support](https://live-litecoin.online/) so that your issue can be looked into.

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by mahamfatima753** [comment]
ok

**Comment by mahamfatima753** [comment]
how you can close my issue without sloving
