### ISSUE TITLE
ETCBI.chain.com

### ISSUE THREAD

**Issue by ETCorps** [blockcypher/explorer#482]
https://github.com/blockcypher/explorer/blob/01f01c04e3b1f6893785a5e3ae949aa237760fb4/templates/home.html#L31

**Comment by hktoor1** [comment]
I do not understand anything about blockchain technology. If you can help me, please do so through my Telegram account, if possible. This is my phone number: 00966566807777‫في 05‏/09‏/2023 الساعة 10:37 ص، كتب/كتبت ***@***.***(CTF); @Extraterestrial1; @Anonymous Satoshi Nakamoto(BTC); @Elliott.Thomas.Cosmos(ETC); @EliottThomasHarbger(ETH); @ElliottThomasFitzwater(ETF) ***@***.***>:‬﻿
https://github.com/blockcypher/explorer/blob/01f01c04e3b1f6893785a5e3ae949aa237760fb4/templates/home.html#L31
Skip to content ETs-FFFSG / -call-exploreActive-WebHooks-for-Token-aadf1081fa5c49de9ef457edf9de873dr-  Type / to search  Code Pull requests Actions Projects Wiki Security Insights Settings We are having a problem billing the Master333-ui-web-et organization. Please update your payment method or call your payment provider for details on why the transaction failed. If the features included in GitHub Free meet your needs, you can downgrade by going to your Billing settings. You can always contact support with any questions. Owner avatar -call-exploreActive-WebHooks-for-Token-aadf1081fa5c49de9ef457edf9de873dr- Public forked from blockcypher/explorer ETs-FFFSG/-call-exploreActive-WebHooks-for-Token-aadf1081fa5c49de9ef457edf9de873dr-  1 branch  0 tags This branch is up to date with blockcypher/explorer:master. Latest commit @quentinlesceller quentinlesceller Remove Metadata and Bump requests from 2.23.0 to 2.31.0 (#474 … 01f01c0 on Jul 10 Git stats  709 commits Files Type Name Latest commit message Commit time addresses Remove webhooks 10 months ago blockexplorer Remove Metadata and Bump requests from 2.23.0 to 2.31.0 (#474 2 months ago blocks Remove sessions last year emails Remove sessions last year homepage Remove sessions last year services Remove webhooks 10 months ago static Remove Metadata and Bump requests from 2.23.0 to 2.31.0 (#474 2 months ago templates Remove Metadata and Bump requests from 2.23.0 to 2.31.0 (#474 2 months ago transactions Remove sessions last year users Remove sessions last year wallets Remove sessions last year .gitignore stashing more changes 8 years ago LICENSE Added license and copyright notice. 9 years ago NOTICE Remove Metadata and Bump requests from 2.23.0 to 2.31.0 (#474 2 months ago Procfile Remove preload 3 years ago README.md Remove webhooks 10 months ago manage.py touch 4 years ago requirements.txt Remove Metadata and Bump requests from 2.23.0 to 2.31.0 (#474 2 months ago runtime.txt Update runtime 4 months ago setup.cfg initial commit 9 years ago utils.py almost working 8 years ago README.md NOTE: While open-source, some features of this block explorer are not easily compatible with running your own version locally, and this is no longer recommended (except for expert users). --  Setup Instructions Install OSX Follow the instructions here to install Homebrew and then (re)install python. If for some reason the step above does not install pip and virtualenv, follow the instructions here to get pip and then install virtualenv using pip install virtualenv. Install the foreman gem for accessing environmental variables: $ gem install foreman Optional (advanced features): Install the latest stable version of postgres 9. (http://postgresapp.com/)[Postgresapp for Mac] is quite easy to install. Ubuntu $ sudo apt-get install postgresql libpq-dev ngrok-client ngrok-server Configure $ cd into your projects/workspaces directory and run $ git clone https://github.com/blockcypher/explorer.git. The result of $ git remote -v should look like this: origin	***@***.***:blockcypher/explorer.git (fetch) origin	***@***.***:blockcypher/explorer.git (push) $ cd explorer/ to get to the project root direction, create a python3 virtual environment ($ virtualenv -p python3 venv) and then activate it ($ source venv/bin/activate) Install requirements: $ pip3 install -r requirements.txt (this will take a few mins) Create a .env file in the project root directory with the following: DEBUG=True TEMPLATE_DEBUG=True ***@***.***:5432/explorer_local SECRET_KEY=RANDOMLY_GENERATED_50CHAR_STRING SITE_DOMAIN=pick_this_yourself.ngrok.com BLOCKCYPHER_API_KEY=PUT_YOURS_HERE (these are for your local machine, production is a little different as settings.py is smartly designed to default to production settings)  Create a database on your local machine with whatever name you like. I recommend explorer_local so it's clear you're working on a local copy. You'll be using this above in DJ_DEFAULT_URL. I've assumed your user is postgres, but you could have a different user. Create DB tables from code (replace foreman with heroku for running on production, which should basically never happen again): # Create tables and run migrations: $ foreman run python3 manage.py migrate Run the Site Locally Run the webserver locally:  $ foreman run python3 manage.py runserver Now visit: http://127.0.0.1:8000/  Submit Your First Pull Request First, pull the latest version of the code from github:  $ git pull origin master Make a new branch:  $ git checkout -b my_branch Make some trivial change and commit it:  $ git commit -am 'my changes' Push it up to github:  $ git push origin my_branch You can submit your pull request here: https://github.com/blockcypher/explorer  Congrats, you're all setup!  Post Setup Instructions Build Awesome Features You're on your own for that.  Git Foo Compare your local version of site to what's on github:  $ git log origin/master..HEAD --oneline About Block explorer showcasing the BlockCypher APIs.  live.blockcypher.com Resources  Readme License  Apache-2.0 license  Activity Stars  0 stars Watchers  0 watching Forks  752 forks Report repository Releases No releases published Create a new release Packages No packages published Publish your first package Languages Python 51.5%   HTML 42.6%   CSS 3.6%   JavaScript 2.3% Suggested Workflows Based on your tech stack Actions Importer Automatically convert CI/CD files to YAML for GitHub Actions. Python Package using Anaconda logo Python Package using Anaconda Create and test a Python package on multiple Python versions using Anaconda for package management. Webpack logo Webpack Build a NodeJS project with npm and webpack. More workflows ***@***.*** ETCBI.chain.com ***@***.*** ***@***.*** ETCBI.chain.com © 2023 GitHub, Inc. Footer navigation Terms Privacy Security Status Docs Contact GitHub Pricing API Training Blog About
