### ISSUE TITLE
'Error no data to embed for OP_RETURN output 1.'

### ISSUE THREAD

**Issue by gregnomis** [blockcypher/explorer#512]
Hey guys, I am baffled on this one.
I successfully create a tx skeleton to Blockcypher's expected format with null-data (OP_RETURN). The data is in hex, and value set to 0. Yet I still get:
`Error creating transaction skeleton: {
  errors: [ { error: 'Error no data to embed for OP_RETURN output 1.' } ],`

Here is my log:
Received hash to submit: 84e4111fc915e6465cc024512b590a93e7fd99bdc4b50f15e45b7cae3c7588ea
Creating and sending transaction...
Preparing to create transaction skeleton.
Creating transaction skeleton with requestBody: {
  "inputs": [
    {
      "addresses": [
        "bc1qu05e8nvpy5f9pyyxs9c76drvksfqsy6gztf70u"
      ]
    }
  ],
  "outputs": [
    {
      "addresses": [
        "bc1quul9kxpd63mghcgj6h5gc7g5c2zqmnmzex94ml"
      ],
      "value": 700
    },
    {
      "script_type": "null-data",
      "data": "84e4111fc915e6465cc024512b590a93e7fd99bdc4b50f15e45b7cae3c7588ea",
      "value": 0
    }
  ],
  "token": "8a2fe74a171c4f379ad2bc3b615510ef"
}

Modified addresses and tokens for obvious reasons.

Any idea? The hash is in the correct hex format, I don't understand why its saying there's no data to embed.
Thanks!

**Comment by CrytoCraze77** [comment]
Why do I give shit you guys throw some badass job seems k8ndw like take away make way for some steal 10;bitcoin from me how many you all get lol ur fuckin fuckers huh?

**Comment by gregnomis** [comment]
Embedded data as ASCII, not hex. For some reason, hex will not be recognized as null-data but ASCII is...
