### ISSUE TITLE
### <span aria-hidden="false">✅</span> Deploy Preview for *my-cashtokens-webwallet* ready!

### ISSUE THREAD

**Issue by Vin757** [blockcypher/explorer#513]
### <span aria-hidden="false">✅</span> Deploy Preview for *my-cashtokens-webwallet* ready!

|  Name | Link |
|:-:|------------------------|
|<span aria-hidden="false">🔨</span> Latest commit | 51663afdd106c619d87e7a6d71f4b80e489550f7 |
|<span aria-hidden="false">🔍</span> Latest deploy log | https://app.netlify.com/sites/my-cashtokens-webwallet/deploys/65c7857f5ad2d90008a89360 |
|<span aria-hidden="false">😎</span> Deploy Preview | [https://deploy-preview-62--my-cashtokens-webwallet.netlify.app](https://deploy-preview-62--my-cashtokens-webwallet.netlify.app) |
|<span aria-hidden="false">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />![QR Code](https://app.netlify.com/qr-code/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJodHRwczovL2RlcGxveS1wcmV2aWV3LTYyLS1teS1jYXNodG9rZW5zLXdlYndhbGxldC5uZXRsaWZ5LmFwcCJ9.by4HEQlcq5WrivdTfFsIhriXmgsCrO1g5eNAzYzSutc)<br /><br />_Use your smartphone camera to open QR code link._</details> |
---

_To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/my-cashtokens-webwallet/configuration/deploys#deploy-notifications)._

_Originally posted by @netlify in https://github.com/cashonize/wallet/pull/62#issuecomment-1937018246_

**Comment by CrytoCraze77** [comment]
Isn’t this you?? 👇Man what you want im no mood argue ?? Sent from my iPhoneOn Feb 19, 2024, at 00:09, Vin757 ***@***.***> wrote:﻿
Closed #513 as completed.

**Comment by CrytoCraze77** [comment]
You be friends with Elon I gotta ask how Many of me is there was there bet you have idea of a count and don’t care cruel Sent from my iPhoneOn Feb 19, 2024, at 00:09, Vin757 ***@***.***> wrote:﻿
Closed #513 as completed.

**Comment by CrytoCraze77** [comment]
Man fix my gear Pleasse I get these all the time iPhone 14 iOS up to dare Verizon and McAfee and nothing WORKSSent from my iPhoneOn Feb 19, 2024, at 00:35, Jeremy M ***@***.***> wrote:﻿Isn’t this you?? 👇<image0.png>Man what you want im no mood argue ?? Sent from my iPhoneOn Feb 19, 2024, at 00:09, Vin757 ***@***.***> wrote:﻿
Closed #513 as completed.
