### ISSUE TITLE
Show Transaction Hex on Transaction Page

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#78]
Waiting on @matthieu to add a `?includeHex=true` parameter to the tx endpoint.

Please assign back to me when ready.

**Comment by matthieu** [comment]
This is implemented. See:

http://dev.blockcypher.com/#validate_tosign

**Comment by mflaxman** [comment]
@matthieu is that the wrong link? The goal here is to take a transaction hash and return the transaction hex to display on the transaction overview page, I don't understand what you sent.

**Comment by matthieu** [comment]
Oh my bad, got confused with signature verification :)

**Comment by NightMachinary** [comment]
@mflaxman How do I use this? (Where should I put `?includeHex=true` in the url `https://live.blockcypher.com/btc-testnet/tx/a1c16af53b8461ef981bf2b1a8f4426b8db42bee88a953848fd71d833d0dffce/`?)
