### ISSUE TITLE
Wallent Name Examples on Homepage Often Don't Work

### ISSUE THREAD

**Issue by mflaxman** [blockcypher/explorer#99]
@techguy613's pull request works great but the examples don't :(

Details here: https://github.com/blockcypher/explorer/pull/98#issuecomment-77117190

**Comment by techguy613** [comment]
Hey Michael,

The addresses have been updated. At this point we support bitcoin, litecoin and dogecoin so perhaps I should empty out the example for the other coins and btc-testnet?

**Comment by mflaxman** [comment]
That sounds great, thanks Matt!

On Thursday, March 5, 2015, Matt David <notifications@github.com> wrote:

> Hey Michael,
>
> The addresses have been updated. At this point we support bitcoin,
> litecoin and dogecoin so perhaps I should empty out the example for the
> other coins and btc-testnet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blockcypher/explorer/issues/99#issuecomment-77205557>.
>


-- 
Sent from my iPhone

**Comment by mflaxman** [comment]
Closing as this was fixed a long time ago. Thanks!
